### ISSUE TITLE
RangeError [ERR_OUT_OF_RANGE]

### ISSUE THREAD

**Issue by william-will-angi** [keycloakify/keycloakify#284]
Unfortunately I can't provide any more information at the moment. Any ideas what could be causing this? It seems to crop up sporadically inside a docker container in our CI env. I haven't seen it happen locally, but I don't build keycloakify locally that often so I'm not 100% it's CI-specific.

Solution is always rebuilding the Dockerfile without the cache.

```

[2023-03-28T22:28:19.623Z] 🔏 Building the keycloak theme...⌚

[2023-03-28T22:28:21.626Z] RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 2031612. Received 2031636

[2023-03-28T22:28:21.626Z]     at new NodeError (node:internal/errors:387:5)

[2023-03-28T22:28:21.626Z]     at boundsError (node:internal/buffer:86:9)

[2023-03-28T22:28:21.626Z]     at Buffer.readUInt32LE (node:internal/buffer:220:5)

[2023-03-28T22:28:21.626Z]     at /opt/ui/node_modules/keycloakify/bin/tools/downloadAndUnzip.js:411:47

[2023-03-28T22:28:21.626Z]     at step (/opt/ui/node_modules/keycloakify/bin/tools/downloadAndUnzip.js:44:23)

[2023-03-28T22:28:21.626Z]     at Object.next (/opt/ui/node_modules/keycloakify/bin/tools/downloadAndUnzip.js:25:53)

[2023-03-28T22:28:21.626Z]     at step (/opt/ui/node_modules/keycloakify/bin/tools/downloadAndUnzip.js:29:139)

[2023-03-28T22:28:21.626Z]     at Object.next (/opt/ui/node_modules/keycloakify/bin/tools/downloadAndUnzip.js:25:53)

[2023-03-28T22:28:21.626Z]     at resume (/opt/ui/node_modules/keycloakify/bin/tools/downloadAndUnzip.js:62:44)

[2023-03-28T22:28:21.626Z]     at /opt/ui/node_modules/keycloakify/bin/tools/downloadAndUnzip.js:61:121

[2023-03-28T22:28:21.626Z]     at new Promise (<anonymous>)

[2023-03-28T22:28:21.626Z]     at Object.i.<computed> [as next] (/opt/ui/node_modules/keycloakify/bin/tools/downloadAndUnzip.js:61:63)

[2023-03-28T22:28:21.626Z]     at /opt/ui/node_modules/keycloakify/bin/tools/downloadAndUnzip.js:289:49

[2023-03-28T22:28:21.626Z]     at step (/opt/ui/node_modules/keycloakify/bin/tools/downloadAndUnzip.js:44:23)

[2023-03-28T22:28:21.626Z]     at Object.next (/opt/ui/node_modules/keycloakify/bin/tools/downloadAndUnzip.js:25:53)

[2023-03-28T22:28:21.626Z]     at fulfilled (/opt/ui/node_modules/keycloakify/bin/tools/downloadAndUnzip.js:16:58) {

[2023-03-28T22:28:21.626Z]   code: 'ERR_OUT_OF_RANGE'

[2023-03-28T22:28:21.626Z] }
```

**Comment by mkreuzmayr** [comment]
For me, these errors also occur randomly in some build operations. All these problems can be traced back to `downloadAndUnzip`. I think that the warning comes from `make-fetch-happen` and the errors happen in the unzip implementation.

<details>
<summary>MaxListenersExceededWarning</summary>

```
(node:49) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Symbol(destroyed) listeners added to [CachingMinipassPipeline]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
```

</details>
<details>
<summary>Z_BUF_ERROR - Error: unexpected end of file</summary>

```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
Emitted 'error' event on InflateRaw instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -5,
  code: 'Z_BUF_ERROR'
}
```

</details>
<details>
<summary>ERR_OUT_OF_RANGE: The value of "offset" is out of range. It must be >= 0 and <= 589822. Received 589830</summary>

```
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 589822. Received 589830
    at new NodeError (node:internal/errors:393:5)
    at boundsError (node:internal/buffer:86:9)
    at Buffer.readUInt16LE (node:internal/buffer:243:5)
    at C:\path\to\my\app\node_modules\keycloakify\bin\tools\downloadAndUnzip.js:413:80
    at step (C:\path\to\my\app\node_modules\keycloakify\bin\tools\downloadAndUnzip.js:44:23)
    at Object.next (C:\path\to\my\app\node_modules\keycloakify\bin\tools\downloadAndUnzip.js:25:53)
    at step (C:\path\to\my\app\node_modules\keycloakify\bin\tools\downloadAndUnzip.js:29:139)
    at Object.next (C:\path\to\my\app\node_modules\keycloakify\bin\tools\downloadAndUnzip.js:25:53)
    at resume (C:\path\to\my\app\node_modules\keycloakify\bin\tools\downloadAndUnzip.js:62:44)
    at C:\path\to\my\app\node_modules\keycloakify\bin\tools\downloadAndUnzip.js:61:121 {
  code: 'ERR_OUT_OF_RANGE'
}
```

</details>
<details>
<summary>Z_BUF_ERROR - Error: unexpected end of file</summary>

```
$ yarn generate-i18n-messages
yarn run v1.22.19
$ ts-node --skipProject scripts/generate-i18n-messages.ts
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17) {
  errno: -5,
  code: 'Z_BUF_ERROR'
}
```

</details>

**Comment by garronej** [comment]
I'm verry sorry about that guys 😞   

We used to rely on `wget` and manage cache manually. We moved to `make-fetch-happen` to make the tool more agnostic to the environement.  
Therer's been some hickup since, we'll address it soon.  
I think there is [this PR](https://github.com/keycloakify/keycloakify/pull/269) from @lordvlad that work on this.

**Comment by treble-snake** [comment]
Getting the same on npm@8.
Interestingly enough, when I switch to npm@9 the error changes to:
```
$ keycloakify --silent
Error: Command failed: npm config get https-proxy
npm ERR! code ENOWORKSPACES
npm ERR! This command does not support workspaces.
```

**Comment by garronej** [comment]
Damn this is getting out of hand.

**Comment by mkreuzmayr** [comment]
To fix these problems, I would use the built in `http` or `https` modules. I would not read them from the npm config if at all I would make them configurable via keycloakify config or env var and use `http-proxy-agent` ([used in vscode](https://github.com/microsoft/vscode/blob/main/package.json#L74)) or `https-proxy-agent` ([used in vscode](https://github.com/microsoft/vscode/blob/main/package.json#L75)).

For unzipping I´d use some tested external library like `yauzl` ([used in vscode](https://github.com/microsoft/vscode/blob/main/package.json#L97)) or `node-stream-zip`.

Already mentioned that in this comment https://github.com/keycloakify/keycloakify/pull/269#issuecomment-1480926216

**Comment by garronej** [comment]
@mkreuzmayr Since you apprear to know what to do and how and since it seems to be a critical issue would you be willing to handle it?  
This part of the code is the realm of @lordvlad but I sure he wouldn't mind.  

Feel free to say no. It would be perfectly understandable.  
Anyway, you already have write access on the repo, if you come up with a fix, just open a PR so that I can have a look before merging but it wont be a long back an forth.

**Comment by mkreuzmayr** [comment]
I can't say exactly when I will be able to fix it. I will have a look today if it´s manageable. 😁

**Comment by garronej** [comment]
I'm very lucky to have guys like you picking interest in Keycloakify 🙏🏻

**Comment by garronej** [comment]
Hold on @mkreuzmayr,  
I'm sorry I missed that but seems like @lordvlad came up with a fix already.

**Comment by garronej** [comment]
Hopefully it's fixed in the latest release, ley me know.

**Comment by mkreuzmayr** [comment]
I updated the starter project but I am getting another error https://github.com/keycloakify/keycloakify/issues/285

**Comment by mkreuzmayr** [comment]
I´ll try it as soon as the new update works. If everything works, there is no need to refactor imo.
If they errors concerning the unzipping stay, I built a function with the same interface using `yauzl` yesterday.

**Comment by garronej** [comment]
> I´ll try it as soon as the new update works. If everything works, there is no need to refactor imo.
If they errors concerning the unzipping stay, I built a function with the same interface using yauzl yesterday.  

Ok got it, I'm very sory I asked you to work on that when there was already a fix.  
Thank you for you reactivity, a new release is being published RN

**Comment by lordvlad** [comment]
> To fix these problems, I would use the built in [`http`](https://nodejs.org/api/http.html) or [`https`](https://nodejs.org/api/https.html) modules. I would not read them from the npm config if at all I would make them configurable via keycloakify config or env var and use [`http-proxy-agent`](https://www.npmjs.com/package/http-proxy-agent) ([used in vscode](https://github.com/microsoft/vscode/blob/main/package.json#L74)) or [`https-proxy-agent`](https://www.npmjs.com/package/https-proxy-agent) ([used in vscode](https://github.com/microsoft/vscode/blob/main/package.json#L75)).

I thinks make-fetch-happen solves this already sufficiently.

About using custom config or npm config for proxies, I would love to stick with npm config, cause you have it already configured once, why would you need to configure it again?

It's rather unfortunate that yarn workspaces doesn't seem to support `npm config` commands. I was looking into using npm as a module to get the config resolved without running `exec` but npm is really convoluted in that regard. And I did not want to replicate the config resolution.

If we _want_ to support yarn workspaces and _want_ to get away from npm config, I'd argue we'd rather try and read the config from .npmrc files at the usual places instead of (or in addition to, for all I care) having keycloakify-specific configuration.

@mkreuzmayr @garronej wdyt?

**Comment by garronej** [comment]
> why would you need to configure it again?  

I'm with you on that.  

> read the config from .npmrc files  

I like the idea of parsing the `.npmrc` files but I'm woried that it might rais some alarms.  
Build tools are not expected to read outside of the CWD, there are sentive informations like the NPM token in the `~/.npmrc` file.  
What are your though on that?

**Comment by lordvlad** [comment]
Well _libraries_ are not expected to read outside CWD, build tools on the other hand are (npm being a build tool itself). Also `XDG_CACHE_HOME` or `XDG_CONFIG_HOME` should be fair game for build tools. Also, since we're calling `npm config` we could use that to exfiltrate secrets if we'd want to, so I don't think it would make much of a difference.

We could be very upfront about that, document clearly what we're doing here and why.

Of course we could circumvent that using keycloakify-specific config. Then maybe add some docs for suggested workarounds

```
export KEYCLOAKIFY_PROXY=$(npm config get proxy) && keycloakify
```

Wouldn't be my first choice, but okayish

**Comment by garronej** [comment]
No, no.  
You convinced me, let's parse the `~/.npmrc` file.  
It seem by far the best option
