### ISSUE TITLE
theme jar file loading error

### ISSUE THREAD

**Issue by myt588** [keycloakify/keycloakify#355]
Hi, 

the latest version v7.12.0 is causing the bundled xxx.jar theme loading error in keycloak.
I believe it has something to do with the changes made here:
<img width="1459" alt="image" src="https://github.com/keycloakify/keycloakify/assets/6250867/76d1fcb8-db4c-4ec7-b289-88c1e8e66a70">

which is causing an extra layer in the `keycloak-themes.json` file

I tried to build our project with 7.12.0 and 7.11.9 below is the result of `keycloak-thems.json`

with 7.11.9, it looks like:
```
{
  "themes": [
    {
      "name": "hello-world",
      "types": [
        "login",
        "account"
      ]
    }
  ]
}
```

with 7.12.0, it looks like:
```
{
  "themes": [
    [
      {
        "name": "hello-world",
        "types": [
          "login",
          "account"
        ]
      }
    ]
  ]
}
```

as you can see, there is an extra wrap of `[ ]` in the themes array.

And this change in the `keycloak-themes.json` is causing the following error in keycloak:
```
ERROR: Build failure: Build failed due to errors
	[error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configureKeycloakSessionFactory threw an exception: java.lang.RuntimeException: Failed to load themes
	at org.keycloak.quarkus.deployment.KeycloakProcessor.loadThemesFromClassPath(KeycloakProcessor.java:379)
	at org.keycloak.quarkus.deployment.KeycloakProcessor.configureKeycloakSessionFactory(KeycloakProcessor.java:363)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `org.keycloak.theme.ClasspathThemeProviderFactory$ThemeRepresentation` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream); line: 3, column: 5] (through reference chain: org.keycloak.theme.ClasspathThemeProviderFactory$ThemesRepresentation["themes"]->java.lang.Object[][0])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1462)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeFromArray(BeanDeserializer.java:648)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:211)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:214)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:24)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3666)
	at org.keycloak.util.JsonSerialization.readValue(JsonSerialization.java:94)
	at org.keycloak.util.JsonSerialization.readValue(JsonSerialization.java:79)
	at org.keycloak.quarkus.deployment.KeycloakProcessor.loadThemesFromClassPath(KeycloakProcessor.java:374)
	... 12 more
```

I downgrade to 7.11.9 and everything works perfectly.
I am wondering if this change is intended for other purposes or if it is just a typo. 
Either way, I hope this gives some insight about the issue.

Best

**Comment by garronej** [comment]
Thank you very much for reporting!

**Comment by garronej** [comment]
And for investigating, you are indeed correct

**Comment by myt588** [comment]
thank you for the prompt patch for this issue! 
I have tested the new version and confirmed that the issue has been resolved.

Thanks again!!

**Comment by garronej** [comment]
Great! Thanks again!
