### ISSUE TITLE
Error when reading loginAction in `logout-confirm.ftl` template

### ISSUE THREAD

**Issue by derlin** [keycloakify/keycloakify#391]
Hello there!

I have an error showing up in the logs when rendering `logout-confirm.ftl` which I believe is the same problem than reported here:
* #357 

I am using keycloak 22.0.0 with keycloakify 7.15.3. When going to the logout page, I get:
```text
SEVERE [freemarker.runtime] (executor-thread-15) Error executing FreeMarker template part in the #attempt block: freemarker.core._TemplateModelException: An error has occurred when reading existing sub-variable "loginAction"; see cause exception! The type of the containing value was: extended_hash+string (org.keycloak.forms.login.freemarker.model.UrlBean wrapped into f.e.b.StringModel)
----
FTL stack trace ("~" means nesting-related):
      - Failed at: #if !object[key]??  [in template "logout-confirm.ftl" in function "ftl_object_to_js_code_declaring_an_object" at line 501, column 21]
      - Reached through: ${ftl_object_to_js_code_declaring_an_...  [in template "logout-confirm.ftl" at line 6, column 17]
----
      at freemarker.ext.beans.BeanModel.get(BeanModel.java:185)
      at freemarker.core.DynamicKeyName.dealWithStringKey(DynamicKeyName.java:166)
      at freemarker.core.DynamicKeyName._eval(DynamicKeyName.java:86)
      at freemarker.core.Expression.eval(Expression.java:101)
      at freemarker.core.ExistsExpression._eval(ExistsExpression.java:49)
      at freemarker.core.Expression.eval(Expression.java:101)
      at freemarker.core.Expression.evalToBoolean(Expression.java:177)
      at freemarker.core.Expression.evalToBoolean(Expression.java:163)
      at freemarker.core.NotExpression.evalToBoolean(NotExpression.java:34)
      at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
      at freemarker.core.Environment.visit(Environment.java:335)
      at freemarker.core.Environment.visit(Environment.java:341)
      at freemarker.core.Environment.visitAttemptRecover(Environment.java:552)
      at freemarker.core.AttemptBlock.accept(AttemptBlock.java:45)
      at freemarker.core.Environment.visit(Environment.java:371)
      at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:291)
      at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
      at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
      at freemarker.core.Environment.visitIteratorBlock(Environment.java:645)
      at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
      at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
      at freemarker.core.Environment.visit(Environment.java:335)
      at freemarker.core.Environment.visit(Environment.java:377)
      at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:877)
      at freemarker.core.Environment.invokeMacro(Environment.java:813)
      at freemarker.core.Environment.invokeFunction(Environment.java:829)
      at freemarker.core.MethodCall._eval(MethodCall.java:65)
      at freemarker.core.Expression.eval(Expression.java:101)
      at freemarker.core.Assignment.accept(Assignment.java:134)
      at freemarker.core.Environment.visit(Environment.java:371)
      at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:291)
      at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
      at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
      at freemarker.core.Environment.visitIteratorBlock(Environment.java:645)
      at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
      at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
      at freemarker.core.Environment.visit(Environment.java:335)
      at freemarker.core.Environment.visit(Environment.java:377)
      at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:877)
      at freemarker.core.Environment.invokeMacro(Environment.java:813)
      at freemarker.core.Environment.invokeFunction(Environment.java:829)
      at freemarker.core.MethodCall._eval(MethodCall.java:65)
      at freemarker.core.Expression.eval(Expression.java:101)
      at freemarker.core.BuiltInsForOutputFormatRelated$AbstractConverterBI.calculateResult(BuiltInsForOutputFormatRelated.java:50)
      at freemarker.core.MarkupOutputFormatBoundBuiltIn._eval(MarkupOutputFormatBoundBuiltIn.java:40)
      at freemarker.core.Expression.eval(Expression.java:101)
      at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:104)
      at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
      at freemarker.core.Environment.visit(Environment.java:335)
      at freemarker.core.Environment.visit(Environment.java:341)
      at freemarker.core.Environment.process(Environment.java:314)
      at freemarker.template.Template.process(Template.java:383)
      at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.processTemplate(DefaultFreeMarkerProvider.java:49)
      at org.keycloak.forms.login.freemarker.FreeMarkerLoginFormsProvider.processTemplate(FreeMarkerLoginFormsProvider.java:549)
      at org.keycloak.forms.login.freemarker.FreeMarkerLoginFormsProvider.createResponse(FreeMarkerLoginFormsProvider.java:305)
      at org.keycloak.forms.login.freemarker.FreeMarkerLoginFormsProvider.createLogoutConfirmPage(FreeMarkerLoginFormsProvider.java:720)
      at org.keycloak.protocol.oidc.endpoints.LogoutEndpoint.displayLogoutConfirmationScreen(LogoutEndpoint.java:320)
      at org.keycloak.protocol.oidc.endpoints.LogoutEndpoint.logout(LogoutEndpoint.java:308)
      at jdk.internal.reflect.GeneratedMethodAccessor231.invoke(Unknown Source)
      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
      at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
      at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
      at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
      at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
      at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
      at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
      at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
      at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
      at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:174)
      at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:142)
      at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
      at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:131)
      at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:33)
      at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
      at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
      at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
      at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
      at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
      at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
      at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
      at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
      at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:84)
      at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:44)
      at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
      at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
      at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
      at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
      at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
      at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
      at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
      at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
      at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
      at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
      at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
      at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
      at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
      at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
      at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
      at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InvocationTargetException
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
      at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1553)
      at freemarker.ext.beans.BeanModel.invokeThroughDescriptor(BeanModel.java:233)
      at freemarker.ext.beans.BeanModel.get(BeanModel.java:152)
      ... 99 more
Caused by: java.lang.RuntimeException: action URI not set
      at org.keycloak.forms.login.freemarker.model.UrlBean.getLoginAction(UrlBean.java:52)
      ... 106 more
```

Would it be possible to add the `logout-confirm.ftl` to the list of exceptions here https://github.com/keycloakify/keycloakify/blob/310f857257335e30108545e00e83caa9b59db148/src/bin/keycloakify/generateFtl/ftl_object_to_js_code_declaring_an_object.ftl#L174-L177 ?

Thank you for this amazing project!

**Comment by garronej** [comment]
Sure!  
Thanks for reporting.  
Can you copy paste here the HTML of the page so I can see precisely what property I should avoid reading.  
(right click -> see source)

**Comment by derlin** [comment]
Sure! Here it is:

```html
<!DOCTYPE html><html lang="en"><head><script>
    window.kcContext=  
(()=>{

    const out = {
    "social": {
        "displayInfo": true,
        "providers": [
            {
                "displayName": "Google Workspace (Divio)",
                "providerId": "saml",
                "loginUrl": "\/realms/internal-nonprod/broker/divio-google-workspace/login?client_id=control-panel-localdev&tab_id=RhMXmBrm0DI&session_code=2FghK3OjaZSAaHBCyNuoM2YAk1rXNjGx7HJNSqPISZg",
                "iconClasses": "",
                "alias": "divio-google-workspace",
            },
            {
                "displayName": "GitHub",
                "providerId": "github",
                "loginUrl": "\/realms/internal-nonprod/broker/github/login?client_id=control-panel-localdev&tab_id=RhMXmBrm0DI&session_code=2FghK3OjaZSAaHBCyNuoM2YAk1rXNjGx7HJNSqPISZg",
                "iconClasses": "fa fa-github",
                "alias": "github",
            },
            {
                "displayName": "Google",
                "providerId": "google",
                "loginUrl": "\/realms/internal-nonprod/broker/google/login?client_id=control-panel-localdev&tab_id=RhMXmBrm0DI&session_code=2FghK3OjaZSAaHBCyNuoM2YAk1rXNjGx7HJNSqPISZg",
                "iconClasses": "fa fa-google",
                "alias": "google",
            },
        ],
    },
    "auth": {
        "showResetCredentials": false,
        "authenticationSelections": [
        ],
        "showUsername": false,
        "showTryAnotherWayLink": false,
    },
    "login": {
    },
    "url": {
        "oauthAction": "\/realms/internal-nonprod/login-actions/consent?client_id=control-panel-localdev&tab_id=RhMXmBrm0DI",
        "resourcesPath": "\/resources/n4gvr/login/divio-cloud",
        /*Couldn't test if 'loginAction' is available on this object*/
        "loginUrl": "\/realms/internal-nonprod/login-actions/authenticate?client_id=control-panel-localdev&tab_id=RhMXmBrm0DI",
        "resourcesCommonPath": "\/resources/n4gvr/common/keycloak",
        "firstBrokerLoginUrl": "\/realms/internal-nonprod/login-actions/first-broker-login?client_id=control-panel-localdev&tab_id=RhMXmBrm0DI",
        "registrationUrl": "\/realms/internal-nonprod/login-actions/registration?client_id=control-panel-localdev&tab_id=RhMXmBrm0DI",
        "logoutConfirmAction": "\/realms/internal-nonprod/protocol/openid-connect/logout/logout-confirm?client_id=control-panel-localdev&tab_id=RhMXmBrm0DI",
        /*If you need 'loginUpdateProfileUrl' on logout-confirm.ftl, please submit an issue to the Keycloakify repo*/
        "registrationAction": "\/realms/internal-nonprod/login-actions/registration?client_id=control-panel-localdev&tab_id=RhMXmBrm0DI",
        "loginResetCredentialsUrl": "\/realms/internal-nonprod/login-actions/reset-credentials?client_id=control-panel-localdev&tab_id=RhMXmBrm0DI",
        /*If you need 'loginUsernameReminderUrl' on logout-confirm.ftl, please submit an issue to the Keycloakify repo*/
        "resourcesUrl": "\/resources/n4gvr?client_id=control-panel-localdev&tab_id=RhMXmBrm0DI/login/divio-cloud",
        "loginRestartFlowUrl": "\/realms/internal-nonprod/login-actions/restart?client_id=control-panel-localdev&tab_id=RhMXmBrm0DI",
        "oauth2DeviceVerificationAction": "\/realms/internal-nonprod/device?client_id=control-panel-localdev&tab_id=RhMXmBrm0DI",
    },
    "messagesPerField": {
    },
    "logoutConfirm": {
        "code": "2FghK3OjaZSAaHBCyNuoM2YAk1rXNjGx7HJNSqPISZg",
        "skipLink": false,
    },
    "client": {
        "clientId": "control-panel-localdev",
        "description": "Local development instance(s) of the Divio Cloud control panel, used by internal and external developers.",
        "baseUrl": "https://control.local.aldryn.net",
        "name": "Control Panel (localdev)",
        "attributes": {
            "oidc.ciba.grant.enabled": "false",
            "client.secret.creation.time": "1689281001",
            "backchannel.logout.session.required": "true",
            "display.on.consent.screen": "false",
            "oauth2.device.authorization.grant.enabled": "false",
            "backchannel.logout.revoke.offline.tokens": "false",
        },
    },
    "realm": {
        "displayName": "Divio (nonprod)",
        "registrationAllowed": true,
        "displayNameHtml": "Divio (nonprod)",
        "resetPasswordAllowed": true,
        "resetCredentialsActionTokenLifespanMinutes": "30",
        "password": true,
        "actionTokenGeneratedByUserLifespanMinutes": "30",
        "internationalizationEnabled": false,
        "idpVerifyAccountLinkActionTokenLifespanMinutes": "30",
        "verifyEmailActionTokenLifespanMinutes": "30",
        "loginWithEmailAllowed": true,
        "duplicateEmailsAllowed": false,
        "editUsernameAllowed": true,
        "name": "internal-nonprod",
        "rememberMe": true,
        "registrationEmailAsUsername": true,
        "identityFederationEnabled": true,
    },
    "scripts": [
    ],
    "properties": {
        "kcLogoIdP-facebook": "fa fa-facebook",
        "parent": "keycloak",
        "kcAuthenticatorOTPClass": "fa fa-mobile list-view-pf-icon-lg",
        "kcLogoIdP-bitbucket": "fa fa-bitbucket",
        "kcAuthenticatorWebAuthnClass": "fa fa-key list-view-pf-icon-lg",
        "kcWebAuthnDefaultIcon": "pficon pficon-key",
        "kcLogoIdP-stackoverflow": "fa fa-stack-overflow",
        "kcSelectAuthListItemClass": "pf-l-stack__item select-auth-box-parent pf-l-split",
        "kcLogoIdP-microsoft": "fa fa-windows",
        "kcLocaleItemClass": "pf-c-dropdown__menu-item",
        "kcLoginOTPListItemHeaderClass": "pf-c-tile__header",
        "kcLoginOTPListItemIconBodyClass": "pf-c-tile__icon",
        "kcInputHelperTextAfterClass": "pf-c-form__helper-text pf-c-form__helper-text-after",
        "kcFormClass": "form-horizontal",
        "kcSelectAuthListClass": "pf-l-stack select-auth-container",
        "kcInputClassRadioCheckboxLabelDisabled": "pf-m-disabled",
        "kcSelectAuthListItemIconClass": "pf-l-split__item select-auth-box-icon",
        "kcRecoveryCodesWarning": "kc-recovery-codes-warning",
        "kcFormSettingClass": "login-pf-settings",
        "kcWebAuthnBLE": "fa fa-bluetooth-b",
        "kcInputWrapperClass": "col-xs-12 col-sm-12 col-md-12 col-lg-12",
        "kcSelectAuthListItemArrowIconClass": "fa fa-angle-right fa-lg",
        "meta": "viewport==width=device-width,initial-scale=1",
        "styles": "css/login.css",
        "kcFeedbackAreaClass": "col-md-12",
        "kcLogoIdP-google": "fa fa-google",
        "kcCheckLabelClass": "pf-c-check__label",
        "kcSelectAuthListItemFillClass": "pf-l-split__item pf-m-fill",
        "kcAuthenticatorDefaultClass": "fa fa-list list-view-pf-icon-lg",
        "kcLogoIdP-gitlab": "fa fa-gitlab",
        "kcFormAreaClass": "col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-8 col-lg-offset-2",
        "kcFormButtonsClass": "col-xs-12 col-sm-12 col-md-12 col-lg-12",
        "kcInputClassRadioLabel": "pf-c-radio__label",
        "kcAuthenticatorWebAuthnPasswordlessClass": "fa fa-key list-view-pf-icon-lg",
        "kcSelectAuthListItemHeadingClass": "pf-l-stack__item select-auth-box-headline pf-c-title",
        "kcInfoAreaClass": "col-xs-12 col-sm-4 col-md-4 col-lg-5 details",
        "kcLogoLink": "http://www.keycloak.org",
        "kcContainerClass": "container-fluid",
        "kcSelectAuthListItemTitle": "select-auth-box-paragraph",
        "kcHtmlClass": "login-pf",
        "kcLoginOTPListItemTitleClass": "pf-c-tile__title",
        "locales": "ar,ca,cs,da,de,el,en,es,fa,fr,fi,hu,it,ja,lt,nl,no,pl,pt-BR,ru,sk,sv,tr,zh-CN",
        "kcLogoIdP-openshift-v4": "pf-icon pf-icon-openshift",
        "kcWebAuthnUnknownIcon": "pficon pficon-key unknown-transport-class",
        "kcFormSocialAccountNameClass": "kc-social-provider-name",
        "kcLogoIdP-openshift-v3": "pf-icon pf-icon-openshift",
        "kcLoginOTPListInputClass": "pf-c-tile__input",
        "kcWebAuthnUSB": "fa fa-usb",
        "kcInputClassRadio": "pf-c-radio",
        "kcWebAuthnKeyIcon": "pficon pficon-key",
        "kcFeedbackInfoIcon": "fa fa-fw fa-info-circle",
        "kcCommonLogoIdP": "kc-social-provider-logo kc-social-gray",
        "stylesCommon": "web_modules/@patternfly/react-core/dist/styles/base.css web_modules/@patternfly/react-core/dist/styles/app.css node_modules/patternfly/dist/css/patternfly.min.css node_modules/patternfly/dist/css/patternfly-additions.min.css lib/pficon/pficon.css",
        "kcRecoveryCodesActions": "kc-recovery-codes-actions",
        "kcFormGroupHeader": "pf-c-form__group",
        "kcFormSocialAccountSectionClass": "kc-social-section kc-social-gray",
        "kcLogoIdP-instagram": "fa fa-instagram",
        "kcAlertClass": "pf-c-alert pf-m-inline",
        "kcHeaderClass": "login-pf-page-header",
        "kcLabelWrapperClass": "col-xs-12 col-sm-12 col-md-12 col-lg-12",
        "kcFormSocialAccountLinkClass": "pf-c-login__main-footer-links-item-link",
        "kcLocaleMainClass": "pf-c-dropdown",
        "kcTextareaClass": "form-control",
        "kcButtonBlockClass": "pf-m-block",
        "kcButtonClass": "pf-c-button",
        "kcWebAuthnNFC": "fa fa-wifi",
        "kcLocaleClass": "col-xs-12 col-sm-1",
        "kcInputClassCheckboxInput": "pf-c-check__input",
        "kcFeedbackErrorIcon": "fa fa-fw fa-exclamation-circle",
        "kcInputLargeClass": "input-lg",
        "kcInputErrorMessageClass": "pf-c-form__helper-text pf-m-error required kc-feedback-text",
        "kcRecoveryCodesList": "kc-recovery-codes-list",
        "kcFormSocialAccountListClass": "pf-c-login__main-footer-links kc-social-links",
        "kcAlertTitleClass": "pf-c-alert__title kc-feedback-text",
        "kcAuthenticatorPasswordClass": "fa fa-unlock list-view-pf-icon-lg",
        "kcCheckInputClass": "pf-c-check__input",
        "kcLogoIdP-linkedin": "fa fa-linkedin",
        "kcLogoIdP-twitter": "fa fa-twitter",
        "kcFeedbackWarningIcon": "fa fa-fw fa-exclamation-triangle",
        "kcResetFlowIcon": "pficon pficon-arrow fa",
        "kcSelectAuthListItemIconPropertyClass": "fa-2x select-auth-box-icon-properties",
        "kcFeedbackSuccessIcon": "fa fa-fw fa-check-circle",
        "kcLoginOTPListClass": "pf-c-tile",
        "kcSrOnlyClass": "sr-only",
        "kcFormSocialAccountListGridClass": "pf-l-grid kc-social-grid",
        "kcButtonDefaultClass": "btn-default",
        "kcFormGroupErrorClass": "has-error",
        "kcSelectAuthListItemDescriptionClass": "pf-l-stack__item select-auth-box-desc",
        "kcSelectAuthListItemBodyClass": "pf-l-split__item pf-l-stack",
        "import": "common/keycloak",
        "kcWebAuthnInternal": "pficon pficon-key",
        "kcSelectAuthListItemArrowClass": "pf-l-split__item select-auth-box-arrow",
        "kcCheckClass": "pf-c-check",
        "kcContentClass": "col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3",
        "kcLogoClass": "login-pf-brand",
        "kcLoginOTPListItemIconClass": "fa fa-mobile",
        "kcLoginClass": "login-pf-page",
        "kcSignUpClass": "login-pf-signup",
        "kcButtonLargeClass": "btn-lg",
        "kcFormCardClass": "card-pf",
        "kcLocaleListClass": "pf-c-dropdown__menu pf-m-align-right",
        "kcInputClass": "pf-c-form-control",
        "kcFormGroupClass": "form-group",
        "kcLogoIdP-paypal": "fa fa-paypal",
        "kcInputClassCheckbox": "pf-c-check",
        "kcRecoveryCodesConfirmation": "kc-recovery-codes-confirmation",
        "kcInputClassRadioInput": "pf-c-radio__input",
        "kcFormSocialAccountListButtonClass": "pf-c-button pf-m-control pf-m-block kc-social-item kc-social-gray",
        "kcInputClassCheckboxLabel": "pf-c-check__label",
        "kcFormOptionsClass": "col-xs-12 col-sm-12 col-md-12 col-lg-12",
        "kcFormHeaderClass": "login-pf-header",
        "kcFormSocialAccountGridItem": "pf-l-grid__item",
        "kcButtonPrimaryClass": "pf-m-primary",
        "kcInputHelperTextBeforeClass": "pf-c-form__helper-text pf-c-form__helper-text-before",
        "kcLogoIdP-github": "fa fa-github",
        "kcLabelClass": "pf-c-form__label pf-c-form__label-text",
    },
};

    out["msg"]= function(){ throw new Error("use import { useKcMessage } from 'keycloakify'"); };
    out["advancedMsg"]= function(){ throw new Error("use import { useKcMessage } from 'keycloakify'"); };

    out["messagesPerField"]= {
    
    
        "printIfExists": function (fieldName, text) {

                    if(fieldName === "totp" ){





                                return undefined;



                    }
                    if(fieldName === "userLabel" ){





                                return undefined;



                    }
                    if(fieldName === "password" ){








                                    return undefined;




                    }
                    if(fieldName === "password-confirm" ){





                                return undefined;



                    }
                    if(fieldName === "username" ){








                                    return undefined;




                    }
                    if(fieldName === "email" ){





                                return undefined;



                    }
                    if(fieldName === "firstName" ){





                                return undefined;



                    }
                    if(fieldName === "lastName" ){





                                return undefined;



                    }
                    if(fieldName === "global" ){





                                return undefined;



                    }

                throw new Error(fieldName + "is probably runtime generated, see: https://docs.keycloakify.dev/limitations#field-names-cant-be-runtime-generated");

        },
        "existsError": function (fieldName) {

                    if(fieldName === "totp" ){





                                return false;



                    }
                    if(fieldName === "userLabel" ){





                                return false;



                    }
                    if(fieldName === "password" ){





                                return false;



                    }
                    if(fieldName === "password-confirm" ){





                                return false;



                    }
                    if(fieldName === "username" ){





                                return false;



                    }
                    if(fieldName === "email" ){





                                return false;



                    }
                    if(fieldName === "firstName" ){





                                return false;



                    }
                    if(fieldName === "lastName" ){





                                return false;



                    }
                    if(fieldName === "global" ){





                                return false;



                    }

                throw new Error(fieldName + "is probably runtime generated, see: https://docs.keycloakify.dev/limitations#field-names-cant-be-runtime-generated");


        },
        "get": function (fieldName) {


                    if(fieldName === "totp" ){



                                    return "";



                    }
                    if(fieldName === "userLabel" ){



                                    return "";



                    }
                    if(fieldName === "password" ){






                                        return "";




                    }
                    if(fieldName === "password-confirm" ){



                                    return "";



                    }
                    if(fieldName === "username" ){






                                        return "";




                    }
                    if(fieldName === "email" ){



                                    return "";



                    }
                    if(fieldName === "firstName" ){



                                    return "";



                    }
                    if(fieldName === "lastName" ){



                                    return "";



                    }
                    if(fieldName === "global" ){



                                    return "";



                    }

                throw new Error(fieldName + "is probably runtime generated, see: https://docs.keycloakify.dev/limitations#field-names-cant-be-runtime-generated");


        },
        "exists": function (fieldName) {

                    if(fieldName === "totp" ){





                                return false;



                    }
                    if(fieldName === "userLabel" ){





                                return false;



                    }
                    if(fieldName === "password" ){





                                return false;



                    }
                    if(fieldName === "password-confirm" ){





                                return false;



                    }
                    if(fieldName === "username" ){





                                return false;



                    }
                    if(fieldName === "email" ){





                                return false;



                    }
                    if(fieldName === "firstName" ){





                                return false;



                    }
                    if(fieldName === "lastName" ){





                                return false;



                    }
                    if(fieldName === "global" ){





                                return false;



                    }

                throw new Error(fieldName + "is probably runtime generated, see: https://docs.keycloakify.dev/limitations#field-names-cant-be-runtime-generated");

        }
    };


    out["keycloakifyVersion"] = "7.15.3";
    out["themeVersion"] = "0.1.0";
    out["themeType"] = "login";
    out["themeName"] = "divio-cloud";
    out["pageId"] = "logout-confirm.ftl";

    return out;

})()
;
</script>

<meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="/resources/n4gvr/login/divio-cloud/build/favicon.ico"><title>Divio</title><link rel="preload" href="/resources/n4gvr/login/divio-cloud/build/fonts/5eec4451-e90c-42e7-b4d8-9b8654a65568.woff2" as="font" type="font/woff2" crossorigin="anonymous"><link rel="preload" href="/resources/n4gvr/login/divio-cloud/build/fonts/2fd3ef81-07ed-45b4-a344-7a0defbdadcf.woff2" as="font" type="font/woff2" crossorigin="anonymous"><link rel="preload" href="/resources/n4gvr/login/divio-cloud/build/fonts/081486f6-ae1e-4fc6-8ab9-6a939e96bbdc.woff2" as="font" type="font/woff2" crossorigin="anonymous"><style>@font-face{font-family:'Helvetica Now';src:url(/resources/n4gvr/login/divio-cloud/build/fonts/5eec4451-e90c-42e7-b4d8-9b8654a65568.woff2) format('woff2'),url(/resources/n4gvr/login/divio-cloud/build/fonts/f7cf763b-e79b-4c28-af92-803e0c3f16d4.woff) format('woff');font-weight:400;font-style:normal}@font-face{font-family:'Helvetica Now';src:url(/resources/n4gvr/login/divio-cloud/build/fonts/2fd3ef81-07ed-45b4-a344-7a0defbdadcf.woff2) format('woff2'),url(/resources/n4gvr/login/divio-cloud/build/fonts/52492279-0374-4238-ba8b-751b50089cf0.woff) format('woff');font-weight:500;font-style:normal}@font-face{font-family:'Helvetica Now';src:url(/resources/n4gvr/login/divio-cloud/build/fonts/081486f6-ae1e-4fc6-8ab9-6a939e96bbdc.woff2) format('woff2'),url(/resources/n4gvr/login/divio-cloud/build/fonts/2acf5951-bff6-44e3-949f-a3fa4de57397.woff) format('woff');font-weight:600;font-style:normal}</style><script defer="defer" src="/resources/n4gvr/login/divio-cloud/build/static/js/main.ebad5f4d.js"></script></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>
```

**Comment by garronej** [comment]
Thank you for reporting!  
A new version is being deployed.

**Comment by derlin** [comment]
Amazing, thank you.

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com
