### ISSUE TITLE
Windows: Error: ENOENT: no such file or directory, scandir 'C:\Wefabricate\Projects\keycloakify-starter\public\keycloak-resources\tmp_suLeKsxId_c5f68d7a\keycloak\account\resources'

### ISSUE THREAD

**Issue by jophuijbers-wf** [keycloakify/keycloakify#467]
I'm having trouble setting up the keycloak [starter project](https://github.com/keycloakify/keycloakify-starter). The error below shows up when running `yarn`. All I did was clone the project and try to start it.

Same error also shows up when running `yarn build-keycloak-theme`

```
yarn install v1.22.19
success Already up-to-date.
$ copy-keycloak-resources-to-public
node:fs:1527
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Wefabricate\Projects\keycloakify-starter\public\keycloak-resources\tmp_suLeKsxId_c5f68d7a\keycloak\account\resources'
    at Object.readdirSync (node:fs:1527:3)
    at crawlRec (C:\Wefabricate\Projects\keycloakify-starter\node_modules\keycloakify\bin\tools\crawl.js:43:35)
    at crawl (C:\Wefabricate\Projects\keycloakify-starter\node_modules\keycloakify\bin\tools\crawl.js:65:5)
    at transformCodebase (C:\Wefabricate\Projects\keycloakify-starter\node_modules\keycloakify\bin\tools\transformCodebase.js:52:50)
    at C:\Wefabricate\Projects\keycloakify-starter\node_modules\keycloakify\bin\keycloakify\generateTheme\downloadKeycloakStaticResources.js:107:63
    at step (C:\Wefabricate\Projects\keycloakify-starter\node_modules\keycloakify\bin\keycloakify\generateTheme\downloadKeycloakStaticResources.js:56:23)
    at Object.next (C:\Wefabricate\Projects\keycloakify-starter\node_modules\keycloakify\bin\keycloakify\generateTheme\downloadKeycloakStaticResources.js:37:53)
    at fulfilled (C:\Wefabricate\Projects\keycloakify-starter\node_modules\keycloakify\bin\keycloakify\generateTheme\downloadKeycloakStaticResources.js:28:58) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Wefabricate\\Projects\\keycloakify-starter\\public\\keycloak-resources\\tmp_suLeKsxId_c5f68d7a\\keycloak\\account\\resources'
}
```

**Comment by garronej** [comment]
Hello @jophuijbers-wf,  
Seems like it's broken for Windows again.  

Thanks for reporting. Can you show me the result of `yarn -v` and `node -v`?  

In the meantime you can use Cgwin or WSL.

**Comment by sorooshjaberi** [comment]
> Hello @jophuijbers-wf, Seems like it's broken for Windows again.
> 
> Thanks for reporting. Can you show me the result of `yarn -v` and `node -v`?
> 
> In the meantime you can use Cgwin or WSL.

Got the same error on ubuntu 
![image](https://github.com/keycloakify/keycloakify/assets/93154421/d6014677-0a0d-4929-9699-aefc5be16f67)

**Comment by garronej** [comment]
@sorooshjaberi Cay you try:  

```bash
rm -rf node_modules public/keycloak-resources
yarn
yarn build-keycloak-theme
```

Thanks

**Comment by sorooshjaberi** [comment]
Thank you @garronej
I wanted to run the `yarn copy-keycloak-resources-to-public` command instead of `yarn build-keycloak-theme`  in order to see the changes in storybook. 
Finally I downgraded my node version to v18.17.0 and it worked.

**Comment by jophuijbers-wf** [comment]
@garronej 

`yarn -v => 1.22.19`
`node -v => v18.18.0`

**Comment by garronej** [comment]
@sorooshjaberi, 

Wait sorry but I'm completely lost.  

> I wanted to run the yarn copy-keycloak-resources-to-public command instead of yarn build-keycloak-theme in order to see the changes in storybook.  

Can you elaborate, I don't understand.   

> Finally I downgraded my node version to v18.17.0 and it worked.  

Downgraded from witch version?  

Seems like @jophuijbers-wf is using this exact version and geting the same problem.  

If any of you can provide a reproduction path it would be of great help

**Comment by jophuijbers-wf** [comment]
I'm sorry,  @garronej what do you mean with "reproduction path"?

**Comment by jophuijbers-wf** [comment]
Tried to `yarn` in a WSL terminal. Got the same error:

```
[4/4] Building fresh packages...
$ copy-keycloak-resources-to-public
node:fs:1514
  const result = binding.readdir(
                         ^

Error: ENOENT: no such file or directory, scandir '/mnt/c/Wefabricate/Projects/keycloakify-starter/public/keycloak-resources/tmp_suLeKsxId_c5f68d7a/keycloak/account/resources'
    at Object.readdirSync (node:fs:1514:26)
    at crawlRec (/mnt/c/Wefabricate/Projects/keycloakify-starter/node_modules/keycloakify/bin/tools/crawl.js:43:35)
    at crawl (/mnt/c/Wefabricate/Projects/keycloakify-starter/node_modules/keycloakify/bin/tools/crawl.js:65:5)
    at transformCodebase (/mnt/c/Wefabricate/Projects/keycloakify-starter/node_modules/keycloakify/bin/tools/transformCodebase.js:52:50)
    at /mnt/c/Wefabricate/Projects/keycloakify-starter/node_modules/keycloakify/bin/keycloakify/generateTheme/downloadKeycloakStaticResources.js:107:63
    at step (/mnt/c/Wefabricate/Projects/keycloakify-starter/node_modules/keycloakify/bin/keycloakify/generateTheme/downloadKeycloakStaticResources.js:56:23)
    at Object.next (/mnt/c/Wefabricate/Projects/keycloakify-starter/node_modules/keycloakify/bin/keycloakify/generateTheme/downloadKeycloakStaticResources.js:37:53)
    at fulfilled (/mnt/c/Wefabricate/Projects/keycloakify-starter/node_modules/keycloakify/bin/keycloakify/generateTheme/downloadKeycloakStaticResources.js:28:58) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/mnt/c/Wefabricate/Projects/keycloakify-starter/public/keycloak-resources/tmp_suLeKsxId_c5f68d7a/keycloak/account/resources'
}

Node.js v20.10.0
error Command failed with exit code 1.
```

**Comment by garronej** [comment]
> I'm sorry, @garronej what do you mean with "reproduction path"?  

A series of steps to reproduce the issue. 

> Tried to yarn in a WSL terminal. Got the same error:

Try downgrading you node version to  v18.17.0 in your WSL environement like @sorooshjaberi did, see if it solves the issue.

**Comment by garronej** [comment]
Well @sorooshjaberi @jophuijbers-wf I tried many things for trying to reproduce the problem but no luck.  

I even started from scratch on a brand new ubuntu with node 20 and it worked.  

https://filedn.com/lYPEPucNMheV19aDu23lK0Q/misc/Screen%20Recording%202023-12-06%20at%2020.00.05.mov

I'm really mistified by this...

**Comment by sorooshjaberi** [comment]
@garronej 
This is the [project I cloned](https://github.com/keycloakify/keycloakify-starter).
The Node version is `v20.10.0`.
The Yarn version is `v1.22.19`
Try `yarn install`
After all packages are installed, the `copy-keycloak-resources-to-public` command will be executed which will cause this error.

**Comment by garronej** [comment]
Will be fixed in the relase that include vite support
