### ISSUE TITLE
Can't build locally

### ISSUE THREAD

**Issue by madroneropaulo** [keycloakify/keycloakify#492]
Hi! I'm trying these instructions https://docs.keycloakify.dev/contributing in order to build a local version of keycloakify, but when I run `yarn link-in-app myApp` Im getting an error. This is the output
```
user@users-MacBook-Pro keycloakify % yarn link-in-app myApp
Error: Command failed: yarn install
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at /Users/user/projects/keycloakify/scripts/link-in-app.ts:104:45
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/user/projects/keycloakify/scripts/link-in-app.ts:104:14)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module.m._compile (/Users/user/projects/keycloakify/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/user/projects/keycloakify/node_modules/ts-node/src/index.ts:1621:12) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(778) [Uint8Array] [
       27,  91,  51,  49, 109,  27,  91,  49, 109,  85, 115,  97,
      103, 101,  32,  69, 114, 114, 111, 114,  27,  91,  50,  50,
      109,  27,  91,  51,  57, 109,  58,  32,  84, 104, 101,  32,
      110, 101,  97, 114, 101, 115, 116,  32, 112,  97,  99, 107,
       97, 103, 101,  32, 100, 105, 114, 101,  99, 116, 111, 114,
      121,  32,  40,  47,  85, 115, 101, 114, 115,  47, 112,  97,
      117, 108, 111, 109,  97, 100, 114, 111, 110, 101, 114, 111,
       47, 112, 114, 111, 106, 101,  99, 116, 115,  47, 102, 114,
      111, 110, 116, 101,
      ... 678 more items
    ],
    Buffer(0) [Uint8Array] []
  ],
  pid: 5364,
  stdout: Buffer(778) [Uint8Array] [
     27,  91,  51,  49, 109,  27,  91,  49, 109,  85, 115,  97,
    103, 101,  32,  69, 114, 114, 111, 114,  27,  91,  50,  50,
    109,  27,  91,  51,  57, 109,  58,  32,  84, 104, 101,  32,
    110, 101,  97, 114, 101, 115, 116,  32, 112,  97,  99, 107,
     97, 103, 101,  32, 100, 105, 114, 101,  99, 116, 111, 114,
    121,  32,  40,  47,  85, 115, 101, 114, 115,  47, 112,  97,
    117, 108, 111, 109,  97, 100, 114, 111, 110, 101, 114, 111,
     47, 112, 114, 111, 106, 101,  99, 116, 115,  47, 102, 114,
    111, 110, 116, 101,
    ... 678 more items
  ],
  stderr: Buffer(0) [Uint8Array] []
}
```
So I wonder if those instructions are up to date?
Also I have a regular keycloakify dependency in package.json in `myApp` like this:
```
//myApp package.json dependencies...
"keycloakify": "^9.1.7",
```
, should I change it to `"keycloakify": "file:../keycloakify/dist",` or something? Thank you!

**Comment by garronej** [comment]
Hi @madroneropaulo!  
Is myApp using yarn?  
Because it seems like `yarn install` in the forein repo dosen't work

**Comment by madroneropaulo** [comment]
Nope, we're using npm. I'll try with yarn. Thanks
