### ISSUE TITLE
Cannot read properties of undefined (reading 'load')

### ISSUE THREAD

**Issue by gift25880** [keycloakify/keycloakify#607]
I use Keycloakify version 9.1.4 with Node version of 20.5.0.
In package.json, I have this script:

`"keycloak": "yarn build && keycloakify"`

after I run` yarn keycloak`, it build successfully but when it try to build the theme, it gives this error and I don't know why.

```
D:\pathToMyProject\node_modules\keycloakify\bin\keycloakify\generateFtl\generateFtl.js:69
    var $ = cheerio_1.default.load(indexHtmlCode);
                              ^

TypeError: Cannot read properties of undefined (reading 'load')
    at generateFtlFilesCodeFactory (D:\pathToMyProject\node_modules\keycloakify\bin\keycloakify\generateFtl\generateFtl.js:69:31)
    at D:\pathToMyProject\node_modules\keycloakify\bin\keycloakify\generateTheme\generateTheme.js:192:106
    at step (D:\pathToMyProject\node_modules\keycloakify\bin\keycloakify\generateTheme\generateTheme.js:56:23)
    at Object.next (D:\pathToMyProject\node_modules\keycloakify\bin\keycloakify\generateTheme\generateTheme.js:37:53)
    at step (D:\pathToMyProject\node_modules\keycloakify\bin\keycloakify\generateTheme\generateTheme.js:41:139)
    at Object.next (D:\pathToMyProject\node_modules\keycloakify\bin\keycloakify\generateTheme\generateTheme.js:37:53)
    at D:\pathToMyProject\node_modules\keycloakify\bin\keycloakify\generateTheme\generateTheme.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (D:\pathToMyProject\node_modules\keycloakify\bin\keycloakify\generateTheme\generateTheme.js:27:12)
    at generateTheme (D:\pathToMyProject\node_modules\keycloakify\bin\keycloakify\generateTheme\generateTheme.js:117:12)

Node.js v20.5.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by garronej** [comment]
Thank you for reporting.  

I've published a patch release for v9 v8 v7 v6 and v5.  
V10 does not have this issue, v10 has no dependencies.

**Comment by garronej** [comment]
for thoses who don't want to update keycloakify you can fix the problem by adding 

```json
{
  "resolutions": {
     "cheerio": "1.0.0-rc.5"
   }
}
```

In your package.json (assuming you're using yarn in your project)
