### ISSUE TITLE
running npx initialize-email-theme got node error

### ISSUE THREAD

**Issue by gift25880** [keycloakify/keycloakify#617]
I use Keycloakify v9.1.4 with node v20.5.0.
I tried to use command `npx initialize-email-theme` and after I selected the Keycloak version, I got this error.

```
Select Keycloak version?
24.0.3
node:internal/errors:865
  const err = new Error(message);
              ^

Error: Command failed: npm install --omit=dev
    at checkExecSyncError (node:child_process:887:11)
    at Object.execSync (node:child_process:959:15)
    at /Users/gift01210/Desktop/innovasive/kss-keycloak/node_modules/keycloakify/bin/download-builtin-keycloak-theme.js:132:63
    at step (/Users/gift01210/Desktop/innovasive/kss-keycloak/node_modules/keycloakify/bin/download-builtin-keycloak-theme.js:57:23)
    at Object.next (/Users/gift01210/Desktop/innovasive/kss-keycloak/node_modules/keycloakify/bin/download-builtin-keycloak-theme.js:38:53)
    at /Users/gift01210/Desktop/innovasive/kss-keycloak/node_modules/keycloakify/bin/download-builtin-keycloak-theme.js:32:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/gift01210/Desktop/innovasive/kss-keycloak/node_modules/keycloakify/bin/download-builtin-keycloak-theme.js:28:12)
    at Object.action (/Users/gift01210/Desktop/innovasive/kss-keycloak/node_modules/keycloakify/bin/download-builtin-keycloak-theme.js:118:44) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 14298,
  stdout: null,
  stderr: null
}

Node.js v20.5.0
```

Is there anything I can deal with?

**Comment by garronej** [comment]
Hello @gift25880,  

Keycloakify 9? If your starting anything new you should start with keycloakify 10.  
Keycloakify 9 isn't compatible with the latest version of Keycloak.  

Anyway, the command works on my machine. Try selecting Keycloak 25.

**Comment by gift25880** [comment]
@garronej Thank you for your reply. At first, I used that command with my Macbook and it failed to run, but when I switched to my Windows PC, it worked perfectly! So this might be some of the OS issues (I guess). Thanks for helping anyway. 😊
