### ISSUE TITLE
Cannot create new story in 10.0.4

### ISSUE THREAD

**Issue by LoiKos** [keycloakify/keycloakify#630]
Hello,

I was following the [Component level customization guide](https://docs.keycloakify.dev/customization-strategies/component-level-customization) using keycloakify `10.0.4` when i faced some troubles running the command to create new story:

```
yarn dlx keycloakify add-story
```
the error:

```
ZodError: [
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_literal",
            "expected": "Multi-Page",
            "path": [
              "keycloakify",
              "accountThemeImplementation"
            ],
            "message": "Invalid literal value, expected \"Multi-Page\""
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_union",
            "unionErrors": [
              {
                "issues": [
                  {
                    "code": "invalid_literal",
                    "expected": "Single-Page",
                    "path": [
                      "keycloakify",
                      "accountThemeImplementation"
                    ],
                    "message": "Invalid literal value, expected \"Single-Page\""
                  }
                ],
                "name": "ZodError"
              },
              {
                "issues": [
                  {
                    "code": "invalid_literal",
                    "expected": "none",
                    "path": [
                      "keycloakify",
                      "accountThemeImplementation"
                    ],
                    "message": "Invalid literal value, expected \"none\""
                  }
                ],
                "name": "ZodError"
              }
            ],
            "path": [
              "keycloakify",
              "accountThemeImplementation"
            ],
            "message": "Invalid input"
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [
      "keycloakify"
    ],
    "message": "Invalid input"
  }
]
    at get error (/Users/llepenn/Dev/lestr/keycloak/src/main/docker/js/node_modules/keycloakify/bin/941.index.js:793:31)
    at ZodObject.parse (/Users/llepenn/Dev/lestr/keycloak/src/main/docker/js/node_modules/keycloakify/bin/941.index.js:892:22)
    at /Users/llepenn/Dev/lestr/keycloak/src/main/docker/js/node_modules/keycloakify/bin/31.index.js:320:35
    at getBuildContext (/Users/llepenn/Dev/lestr/keycloak/src/main/docker/js/node_modules/keycloakify/bin/31.index.js:321:7)
    at command (/Users/llepenn/Dev/lestr/keycloak/src/main/docker/js/node_modules/keycloakify/bin/97.index.js:40:104)
    at handler (/Users/llepenn/Dev/lestr/keycloak/src/main/docker/js/node_modules/keycloakify/bin/main.js:11388:15)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:545:9)
    at process.processTimers (node:internal/timers:519:7)
    at async /Users/llepenn/Dev/lestr/keycloak/src/main/docker/js/node_modules/keycloakify/bin/main.js:11245:1145 {
  issues: [
    {
      code: 'invalid_union',
      unionErrors: [Array],
      path: [Array],
      message: 'Invalid input'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_union',
      unionErrors: [Array],
      path: [Array],
      message: 'Invalid input'
    }
  ]
}
```

vite.config.ts :

```ts
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { keycloakify } from 'keycloakify/vite-plugin'
import path from 'path'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    keycloakify({
      accountThemeImplementation: "none"
    }),
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
})

```

**Comment by garronej** [comment]
Hello @LoiKos,  

`yarn dlx` is not the equivalent of `npx`.  

dlx will download whatever is the latest version of keycloakify and run it in a temporary environement.  

This is not what you want to do. You want to run your locally installed version of Keycloakify in your current working directory.  

Use:  

```bash
npx keycloakify add-story
```

**Comment by LoiKos** [comment]
I try with `npx` and i faced the same issue!

```sh
❯ npx keycloakify add-story
ZodError: [
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_literal",
            "expected": "Multi-Page",
            "path": [
              "keycloakify",
              "accountThemeImplementation"
            ],
            "message": "Invalid literal value, expected \"Multi-Page\""
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_union",
            "unionErrors": [
              {
                "issues": [
                  {
                    "code": "invalid_literal",
                    "expected": "Single-Page",
                    "path": [
                      "keycloakify",
                      "accountThemeImplementation"
                    ],
                    "message": "Invalid literal value, expected \"Single-Page\""
                  }
                ],
                "name": "ZodError"
              },
              {
                "issues": [
                  {
                    "code": "invalid_literal",
                    "expected": "none",
                    "path": [
                      "keycloakify",
                      "accountThemeImplementation"
                    ],
                    "message": "Invalid literal value, expected \"none\""
                  }
                ],
                "name": "ZodError"
              }
            ],
            "path": [
              "keycloakify",
              "accountThemeImplementation"
            ],
            "message": "Invalid input"
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [
      "keycloakify"
    ],
    "message": "Invalid input"
  }
]
    at get error (/Users/llepenn/Dev/lestr/keycloak/src/main/docker/js/node_modules/keycloakify/bin/941.index.js:793:31)
    at ZodObject.parse (/Users/llepenn/Dev/lestr/keycloak/src/main/docker/js/node_modules/keycloakify/bin/941.index.js:892:22)
    at /Users/llepenn/Dev/lestr/keycloak/src/main/docker/js/node_modules/keycloakify/bin/31.index.js:320:35
    at getBuildContext (/Users/llepenn/Dev/lestr/keycloak/src/main/docker/js/node_modules/keycloakify/bin/31.index.js:321:7)
    at command (/Users/llepenn/Dev/lestr/keycloak/src/main/docker/js/node_modules/keycloakify/bin/97.index.js:40:104)
    at handler (/Users/llepenn/Dev/lestr/keycloak/src/main/docker/js/node_modules/keycloakify/bin/main.js:11388:15)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:545:9)
    at process.processTimers (node:internal/timers:519:7)
    at async /Users/llepenn/Dev/lestr/keycloak/src/main/docker/js/node_modules/keycloakify/bin/main.js:11245:1145 {
  issues: [
    {
      code: 'invalid_union',
      unionErrors: [Array],
      path: [Array],
      message: 'Invalid input'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_union',
      unionErrors: [Array],
      path: [Array],
      message: 'Invalid input'
    }
  ]
}
```

It might come from my setup. 
I try to migrate from a previous theme from inside a monorepo (i may have conflict coming from here). 
I need to retry later from an empty repo.

**Comment by garronej** [comment]
Ah ok that makes sence.  

What is probably hapening is that you still have the keycloakify options in you package.json.  

If you are using Vite all the options related to Keycloakify must be provided in the vite.config.ts to the keycloakify vite plugin.  

So, remove the `"keycloakify"` field from your `package.json` and it should work.  

Also, there's now a guide for integration with monorepos I don't know if you saw:  

https://docs.keycloakify.dev/keycloakify-in-my-codebase/as-a-subproject-of-your-monorepo

**Comment by LoiKos** [comment]
Oh i see, it was that, i just remove the "keycloakify" field from your package.json and it work now. 
Thank you !

PS: Thanks to share monorepo guide but it's not relevant in my case ;)

**Comment by garronej** [comment]
You might want to checkout this then: https://docs.keycloakify.dev/faq-and-help/migration-guides/v9-greater-than-v10

bye :)
