### ISSUE TITLE
Infinite loop when calling toJsDeclarationString in templates.

### ISSUE THREAD

**Issue by st3r30t1p** [keycloakify/keycloakify#658]
Hi guys.
I'm trying to integrate keycloakify into an existing project and I ran into that infinite loop problem.
The problem occurs when calling https://localhost:8080/auth/realms/myrealm/protocol/openid-connect/auth?client_id=myclient... the request continues to be in the pending state for a long time, and the CPU load on the docker container increases very much. I have to kill the docker to stop it.
After a little debugging, I found that this happens inside the `toJsDeclarationString` function. To make sure, I simply replaced the call to this function with an empty object and after that the problem went away.
I'm not very good at freemarker, but I decided to look at what the `.data_model` contains and this is what I got:

        msg
        relayStateClientId
        ztnaRedirectUri
        auth
        initRequestUri
        turnstileLanguage
        requiredActionUrl
        login
        relayStateClient
        ztnaTargetClientId
        authenticationSession
        fullRealmSocial
        customBackgroundExist
        hiddenAllowedIDPs
        client
        scripts
        customBackgroundEnable
        customLogoExist
        execution
        turnstileSiteKey
        passwordPolicy
        social
        allowedOpeners
        allowedIdentityProviders
        customLogoEnable
        customBackgroundNumber
        ztnaTargetClientName
        url
        advancedMsg
        messagesPerField
        turnstileRequired
        legalAgeCountriesSupported
        targetClient
        realm
        kcSanitize
        properties
        domainsToSkipLa

How do you think the .data_model could break the function?

keycloakify: v10.1.0
keycloak: v25.0.4

**Comment by garronej** [comment]
Hello @st3r30t1p,  

Thanks for reporting.  
If you can give me presice reproduction steps I can easily fix this.  

If it needs some special configuration to be reproducable you can dump the realm configuration and give me the json

It's explained here:
https://www.youtube.com/watch?v=lMOLrdqilqE&t=991s

**Comment by garronej** [comment]
You probably need a custom exclusing for domainsToSkipLa:  

`vite.config.ts`
```ts
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { keycloakify } from "keycloakify/vite-plugin";

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [
        react(),
        keycloakify({
            // ...
            kcContextExclusionsFtl: `
                <#if (
                    key == "domainsToSkipLa" &&
                    areSamePath(path, []) 
                )>
                    <#continue>
                </#if>
            `
        })
    ]
});
```  

Maybe it's one of the other property you listed and not domainsToSkipLa I let you do your trial and error.  

Documentation: https://docs.keycloakify.dev/configuration-options/kccontextexclusionsftl

**Comment by dmit4git** [comment]
Looks like I faced the same issue.

I made a login [theme](https://github.com/dmit4git/full-plate/tree/main/keycloak/keycloakify) based on keycloak v25.0.2 and it works [fine](https://accounts.fullplate.dev/realms/fullplate/protocol/openid-connect/auth?client_id=fullplate-webapp&redirect_uri=https%3A%2F%2Ffullplate.dev%2F&response_type=code&scope=openid&state=e88f49f91b564739851259d6b513974e&code_challenge=vM6SZ0OpKBZ8RjebJCQWNp7PBPA6Emj9NwYaGUueAeo&code_challenge_method=S256&label=Viva&color=&mode=dark), but if I upgrade keycloak to v26.0.7, then the login page with my theme never finishes loading and keycloak indefinitely spams an error related to `toJsDeclarationString`, see the error quote below. Keycloak v26.0.7 works with no issues on default themes (base, keycloak, kecloak.V2).

Pls let me know if I can provide any additional debug info, as I'm not familiar with FreeMaker.

> keycloak           | 2025-01-07 22:37:45,352 SEVERE [freemarker.runtime] (executor-thread-1) Error executing FreeMarker template part in the #attempt block: freemarker.core._TemplateModelException: An error has occurred when reading existing sub-variable "genericDeclaration"; see cause exception! The type of the containing value was: extended_hash+string (sun.reflect.generics.reflectiveObjects.TypeVariableImpl wrapped into f.e.b.StringModel)
> keycloak           | 
> keycloak           | ----
> keycloak           | FTL stack trace ("~" means nesting-related):
> keycloak           |    - Failed at: #if !object[key]??  [in template "login.ftl" in function "toJsDeclarationString" at line 268, column 17]
> keycloak           |    - Reached through: ${toJsDeclarationString(.data_model, ...  [in template "login.ftl" at line 20, column 19]
> keycloak           | ----
> keycloak           |    at freemarker.ext.beans.BeanModel.get(BeanModel.java:185)
> keycloak           |    at freemarker.core.DynamicKeyName.dealWithStringKey(DynamicKeyName.java:166)
> keycloak           |    at freemarker.core.DynamicKeyName._eval(DynamicKeyName.java:86)
> keycloak           |    at freemarker.core.Expression.eval(Expression.java:101)
> keycloak           |    at freemarker.core.ExistsExpression._eval(ExistsExpression.java:49)
> keycloak           |    at freemarker.core.Expression.eval(Expression.java:101)
> keycloak           |    at freemarker.core.Expression.evalToBoolean(Expression.java:177)
> keycloak           |    at freemarker.core.Expression.evalToBoolean(Expression.java:163)
> keycloak           |    at freemarker.core.NotExpression.evalToBoolean(NotExpression.java:34)
> keycloak           |    at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:335)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:341)
> keycloak           |    at freemarker.core.Environment.visitAttemptRecover(Environment.java:552)
> keycloak           |    at freemarker.core.AttemptBlock.accept(AttemptBlock.java:45)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:371)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:291)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
> keycloak           |    at freemarker.core.Environment.visitIteratorBlock(Environment.java:645)
> keycloak           |    at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
> keycloak           |    at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:335)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:377)
> keycloak           |    at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:877)
> keycloak           |    at freemarker.core.Environment.invokeMacro(Environment.java:813)
> keycloak           |    at freemarker.core.Environment.invokeFunction(Environment.java:829)
> keycloak           |    at freemarker.core.MethodCall._eval(MethodCall.java:65)
> keycloak           |    at freemarker.core.Expression.eval(Expression.java:101)
> keycloak           |    at freemarker.core.Assignment.accept(Assignment.java:134)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:371)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:291)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
> keycloak           |    at freemarker.core.Environment.visitIteratorBlock(Environment.java:645)
> keycloak           |    at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
> keycloak           |    at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:335)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:377)
> keycloak           |    at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:877)
> keycloak           |    at freemarker.core.Environment.invokeMacro(Environment.java:813)
> keycloak           |    at freemarker.core.Environment.invokeFunction(Environment.java:829)
> keycloak           |    at freemarker.core.MethodCall._eval(MethodCall.java:65)
> keycloak           |    at freemarker.core.Expression.eval(Expression.java:101)
> keycloak           |    at freemarker.core.Assignment.accept(Assignment.java:134)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:371)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
> keycloak           |    at freemarker.core.Environment.visitIteratorBlock(Environment.java:645)
> keycloak           |    at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
> keycloak           |    at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:335)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:377)
> keycloak           |    at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:877)
> keycloak           |    at freemarker.core.Environment.invokeMacro(Environment.java:813)
> keycloak           |    at freemarker.core.Environment.invokeFunction(Environment.java:829)
> keycloak           |    at freemarker.core.MethodCall._eval(MethodCall.java:65)
> keycloak           |    at freemarker.core.Expression.eval(Expression.java:101)
> keycloak           |    at freemarker.core.Assignment.accept(Assignment.java:134)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:371)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:291)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
> keycloak           |    at freemarker.core.Environment.visitIteratorBlock(Environment.java:645)
> keycloak           |    at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
> keycloak           |    at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:335)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:377)
> keycloak           |    at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:877)
> keycloak           |    at freemarker.core.Environment.invokeMacro(Environment.java:813)
> keycloak           |    at freemarker.core.Environment.invokeFunction(Environment.java:829)
> keycloak           |    at freemarker.core.MethodCall._eval(MethodCall.java:65)
> keycloak           |    at freemarker.core.Expression.eval(Expression.java:101)
> keycloak           |    at freemarker.core.Assignment.accept(Assignment.java:134)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:371)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:291)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
> keycloak           |    at freemarker.core.Environment.visitIteratorBlock(Environment.java:645)
> keycloak           |    at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
> keycloak           |    at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:335)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:377)
> keycloak           |    at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:877)
> keycloak           |    at freemarker.core.Environment.invokeMacro(Environment.java:813)
> keycloak           |    at freemarker.core.Environment.invokeFunction(Environment.java:829)
> keycloak           |    at freemarker.core.MethodCall._eval(MethodCall.java:65)
> keycloak           |    at freemarker.core.Expression.eval(Expression.java:101)
> keycloak           |    at freemarker.core.Assignment.accept(Assignment.java:134)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:371)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
> keycloak           |    at freemarker.core.Environment.visitIteratorBlock(Environment.java:645)
> keycloak           |    at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
> keycloak           |    at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:335)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:377)
> keycloak           |    at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:877)
> keycloak           |    at freemarker.core.Environment.invokeMacro(Environment.java:813)
> keycloak           |    at freemarker.core.Environment.invokeFunction(Environment.java:829)
> keycloak           |    at freemarker.core.MethodCall._eval(MethodCall.java:65)
> keycloak           |    at freemarker.core.Expression.eval(Expression.java:101)
> keycloak           |    at freemarker.core.Assignment.accept(Assignment.java:134)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:371)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:291)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
> keycloak           |    at freemarker.core.Environment.visitIteratorBlock(Environment.java:645)
> keycloak           |    at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
> keycloak           |    at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:335)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:377)
> keycloak           |    at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:877)
> keycloak           |    at freemarker.core.Environment.invokeMacro(Environment.java:813)
> keycloak           |    at freemarker.core.Environment.invokeFunction(Environment.java:829)
> keycloak           |    at freemarker.core.MethodCall._eval(MethodCall.java:65)
> keycloak           |    at freemarker.core.Expression.eval(Expression.java:101)
> keycloak           |    at freemarker.core.Assignment.accept(Assignment.java:134)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:371)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:291)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
> keycloak           |    at freemarker.core.Environment.visitIteratorBlock(Environment.java:645)
> keycloak           |    at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
> keycloak           |    at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:335)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:377)
> keycloak           |    at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:877)
> keycloak           |    at freemarker.core.Environment.invokeMacro(Environment.java:813)
> keycloak           |    at freemarker.core.Environment.invokeFunction(Environment.java:829)
> keycloak           |    at freemarker.core.MethodCall._eval(MethodCall.java:65)
> keycloak           |    at freemarker.core.Expression.eval(Expression.java:101)
> keycloak           |    at freemarker.core.Assignment.accept(Assignment.java:134)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:371)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:291)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
> keycloak           |    at freemarker.core.Environment.visitIteratorBlock(Environment.java:645)
> keycloak           |    at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
> keycloak           |    at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:335)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:377)
> keycloak           |    at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:877)
> keycloak           |    at freemarker.core.Environment.invokeMacro(Environment.java:813)
> keycloak           |    at freemarker.core.Environment.invokeFunction(Environment.java:829)
> keycloak           |    at freemarker.core.MethodCall._eval(MethodCall.java:65)
> keycloak           |    at freemarker.core.Expression.eval(Expression.java:101)
> keycloak           |    at freemarker.core.Assignment.accept(Assignment.java:134)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:371)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:291)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
> keycloak           |    at freemarker.core.Environment.visitIteratorBlock(Environment.java:645)
> keycloak           |    at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
> keycloak           |    at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:335)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:377)
> keycloak           |    at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:877)
> keycloak           |    at freemarker.core.Environment.invokeMacro(Environment.java:813)
> keycloak           |    at freemarker.core.Environment.invokeFunction(Environment.java:829)
> keycloak           |    at freemarker.core.MethodCall._eval(MethodCall.java:65)
> keycloak           |    at freemarker.core.Expression.eval(Expression.java:101)
> keycloak           |    at freemarker.core.Assignment.accept(Assignment.java:134)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:371)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:291)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
> keycloak           |    at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
> keycloak           |    at freemarker.core.Environment.visitIteratorBlock(Environment.java:645)
> keycloak           |    at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
> keycloak           |    at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:335)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:377)
> keycloak           |    at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:877)
> keycloak           |    at freemarker.core.Environment.invokeMacro(Environment.java:813)
> keycloak           |    at freemarker.core.Environment.invokeFunction(Environment.java:829)
> keycloak           |    at freemarker.core.MethodCall._eval(MethodCall.java:65)
> keycloak           |    at freemarker.core.Expression.eval(Expression.java:101)
> keycloak           |    at freemarker.core.BuiltInsForOutputFormatRelated$AbstractConverterBI.calculateResult(BuiltInsForOutputFormatRelated.java:50)
> keycloak           |    at freemarker.core.MarkupOutputFormatBoundBuiltIn._eval(MarkupOutputFormatBoundBuiltIn.java:40)
> keycloak           |    at freemarker.core.Expression.eval(Expression.java:101)
> keycloak           |    at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:104)
> keycloak           |    at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:335)
> keycloak           |    at freemarker.core.Environment.visit(Environment.java:341)
> keycloak           |    at freemarker.core.Environment.process(Environment.java:314)
> keycloak           |    at freemarker.template.Template.process(Template.java:383)
> keycloak           |    at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.processTemplate(DefaultFreeMarkerProvider.java:49)
> keycloak           |    at org.keycloak.forms.login.freemarker.FreeMarkerLoginFormsProvider.processTemplate(FreeMarkerLoginFormsProvider.java:577)
> keycloak           |    at org.keycloak.forms.login.freemarker.FreeMarkerLoginFormsProvider.createResponse(FreeMarkerLoginFormsProvider.java:328)
> keycloak           |    at org.keycloak.forms.login.freemarker.FreeMarkerLoginFormsProvider.createLoginUsernamePassword(FreeMarkerLoginFormsProvider.java:591)
> keycloak           |    at org.keycloak.authentication.authenticators.browser.UsernamePasswordForm.challenge(UsernamePasswordForm.java:93)
> keycloak           |    at org.keycloak.authentication.authenticators.browser.UsernamePasswordForm.authenticate(UsernamePasswordForm.java:79)
> keycloak           |    at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:465)
> keycloak           |    at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:269)
> keycloak           |    at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:400)
> keycloak           |    at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:291)
> keycloak           |    at org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1074)
> keycloak           |    at org.keycloak.authentication.AuthenticationProcessor.authenticate(AuthenticationProcessor.java:912)
> keycloak           |    at org.keycloak.protocol.AuthorizationEndpointBase.handleBrowserAuthenticationRequest(AuthorizationEndpointBase.java:147)
> keycloak           |    at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildAuthorizationCodeAuthorizationResponse(AuthorizationEndpoint.java:353)
> keycloak           |    at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.process(AuthorizationEndpoint.java:204)
> keycloak           |    at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildGet(AuthorizationEndpoint.java:115)
> keycloak           |    at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint$quarkusrestinvoker$buildGet_4b690b27439f19dd29733dc5fd4004f24de0adb6.invoke(Unknown Source)
> keycloak           |    at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
> keycloak           |    at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
> keycloak           |    at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
> keycloak           |    at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
> keycloak           |    at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
> keycloak           |    at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
> keycloak           |    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
> keycloak           |    at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
> keycloak           |    at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
> keycloak           |    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> keycloak           |    at java.base/java.lang.Thread.run(Thread.java:1583)
> keycloak           | Caused by: java.lang.IllegalAccessException: class freemarker.ext.beans.BeansWrapper cannot access class sun.reflect.generics.reflectiveObjects.TypeVariableImpl (in module java.base) because module java.base does not export sun.reflect.generics.reflectiveObjects to unnamed module @4afcd809
> keycloak           |    at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:394)
> keycloak           |    at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:714)
> keycloak           |    at java.base/java.lang.reflect.Method.invoke(Method.java:571)
> keycloak           |    at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1553)
> keycloak           |    at freemarker.ext.beans.BeanModel.invokeThroughDescriptor(BeanModel.java:233)
> keycloak           |    at freemarker.ext.beans.BeanModel.get(BeanModel.java:152)
> keycloak           |    ... 214 more

**Comment by garronej** [comment]
Hello @dmit4git,

You're using a version of Keycloakify that predates the release of Keycloak 26. To resolve the issue, simply update to the latest version of Keycloakify. There are no breaking changes, except that for Keycloak 26, you should use the JAR file named `keycloak-theme-for-all-other-versions.jar`.

- [Deployment Documentation](https://docs.keycloakify.dev/deploying-your-theme)  
- [Keycloak Version Targets](https://docs.keycloakify.dev/features/compiler-options/keycloakversiontargets)

While I strive to maintain backward compatibility with older Keycloak versions, I can't predict breaking changes introduced by future Keycloak releases.

Here’s how compatibility works:  
All themes built with Keycloakify are compatible with all Keycloak versions available **at the time** the Keycloakify version was released.  
To ensure compatibility with the latest Keycloak major release, make sure you are using the latest minor release of the Keycloakify major version you are working with.
