### ISSUE TITLE
When passing `npx keycloakify start-keycloak --keycloak-version 26` getting `TypeError: versionStr.match is not a function`

### ISSUE THREAD

**Issue by corneliusroemer** [keycloakify/keycloakify#730]
When running:

```
$ npx keycloakify start-keycloak --keycloak-version 26
```

I get an error:

```
$ npx keycloakify start-keycloak --keycloak-version 26
TypeError: versionStr.match is not a function
    at Object.parse (/Users/corneliusromer/code/loculus/keycloak/keycloakify/node_modules/keycloakify/bin/20.index.js:341:34)
    at /Users/corneliusromer/code/loculus/keycloak/keycloakify/node_modules/keycloakify/bin/526.index.js:280:47
    at command (/Users/corneliusromer/code/loculus/keycloak/keycloakify/node_modules/keycloakify/bin/526.index.js:295:7)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:555:9)
    at process.processTimers (node:internal/timers:529:7)
    at async handler (/Users/corneliusromer/code/loculus/keycloak/keycloakify/node_modules/keycloakify/bin/main.js:16244:9)
    at async /Users/corneliusromer/code/loculus/keycloak/keycloakify/node_modules/keycloakify/bin/main.js:15385:1145
    at async /Users/corneliusromer/code/loculus/keycloak/keycloakify/node_modules/keycloakify/bin/main.js:15385:2646
    at async Object.enable (/Users/corneliusromer/code/loculus/keycloak/keycloakify/node_modules/keycloakify/bin/main.js:15384:338)
```

```
$ npx keycloakify -v
11.3.24

$ node -v
v22.11.0
```

**Comment by garronej** [comment]
Hello @corneliusroemer,   

The error is missleading, I fixed it. The version should be an actual Keycloak version like `26.0.4` providing only the major is not supported.  

<img width="750" alt="image" src="https://github.com/user-attachments/assets/1a98ec54-f16c-4bcf-87ef-4690172ef0ce">
